enum EImageCode {
  AllanMunger = 'AllanMunger',
  AmandaBrady = 'AmandaBrady',
  AshleyMcCarthy = 'AshleyMcCarthy',
  CarlosSlattery = 'CarlosSlattery',
  CarolePoland = 'CarolePoland',
  CecilFolk = 'CecilFolk',
  CelesteBurton = 'CelesteBurton',
  CharlotteWaltson = 'CharlotteWaltson',
  ColinBallinger = 'ColinBallinger',
  DaisyPhillips = 'DaisyPhillips',
  ElliotWoodward = 'ElliotWoodward',
  ElviaAtkins = 'ElviaAtkins',
  ErikNason = 'ErikNason',
  HenryBrill = 'HenryBrill',
  IsaacFielder = 'IsaacFielder',
  JohnieMcConnell = 'JohnieMcConnell',
  Katlarsson = 'Katlarsson',
  KatriAhokas = 'KatriAhokas',
  KevinSturgis = 'KevinSturgis',
  KristinPatterson = 'KristinPatterson',
  LydiaBauer = 'LydiaBauer',
  MauricioAugust = 'MauricioAugust',
  MiguelGarcia = 'MiguelGarcia',
  MonaKane = 'MonaKane',
  RobertTolbert = 'RobertTolbert',
  RobinCounts = 'RobinCounts',
  TimDeboer = 'TimDeboer',
  WandaHoward = 'WandaHoward',
}

export const localAvatarImageSource: Record<string, number> = {
  [EImageCode.AllanMunger]: require('@assets/AllanMunger.webp'),
  [EImageCode.AmandaBrady]: require('@assets/AmandaBrady.webp'),
  [EImageCode.AshleyMcCarthy]: require('@assets/AshleyMcCarthy.webp'),
  [EImageCode.CarlosSlattery]: require('@assets/CarlosSlattery.webp'),
  [EImageCode.CarolePoland]: require('@assets/CarolePoland.webp'),
  [EImageCode.CecilFolk]: require('@assets/CecilFolk.webp'),
  [EImageCode.CelesteBurton]: require('@assets/CelesteBurton.webp'),
  [EImageCode.CharlotteWaltson]: require('@assets/CharlotteWaltson.webp'),
  [EImageCode.ColinBallinger]: require('@assets/ColinBallinger.webp'),
  [EImageCode.DaisyPhillips]: require('@assets/DaisyPhillips.webp'),
  [EImageCode.ElliotWoodward]: require('@assets/ElliotWoodward.webp'),
  [EImageCode.ElviaAtkins]: require('@assets/ElviaAtkins.webp'),
  [EImageCode.ErikNason]: require('@assets/ErikNason.webp'),
  [EImageCode.IsaacFielder]: require('@assets/IsaacFielder.webp'),
  [EImageCode.JohnieMcConnell]: require('@assets/JohnieMcConnell.webp'),
  [EImageCode.Katlarsson]: require('@assets/Katlarsson.webp'),
  [EImageCode.KatriAhokas]: require('@assets/KatriAhokas.webp'),
  [EImageCode.KevinSturgis]: require('@assets/KevinSturgis.webp'),
  [EImageCode.KristinPatterson]: require('@assets/KristinPatterson.webp'),
  [EImageCode.LydiaBauer]: require('@assets/LydiaBauer.webp'),
  [EImageCode.MauricioAugust]: require('@assets/MauricioAugust.webp'),
  [EImageCode.MiguelGarcia]: require('@assets/MiguelGarcia.webp'),
  [EImageCode.MonaKane]: require('@assets/MonaKane.webp'),
  [EImageCode.RobertTolbert]: require('@assets/RobertTolbert.webp'),
  [EImageCode.RobinCounts]: require('@assets/RobinCounts.webp'),
  [EImageCode.HenryBrill]: require('@assets/HenryBrill.webp'),
  [EImageCode.TimDeboer]: require('@assets/TimDeboer.webp'),
  [EImageCode.WandaHoward]: require('@assets/WandaHoward.webp'),
};
